## Extracting Data from different source and saving it in Data lake (Minio Bucket)
### Let's Understand the data sources and extraction strategy

The simulation environment emulates a realistic e-commerce ecosystem by serving data from multiple heterogeneous sources with different update patterns. 
- Static reference data (customers, products, and sellers) resides in a PostgreSQL OLTP database and is extracted periodically as snapshots.
- Continuously changing transactional tables (orders and order_items) are ingested incrementally in batches as new records arrive. 
- Payment and review events are streamed as append-only Parquet files from an external MinIO S3 bucket.
- Geolocation and translation reference data are retrieved from rarely changing REST API endpoints.

### Take you time and Observe the data sources in action
#### Before we start extracting data, run the simulation in background and observe the data sources in action. The simulation will generate new events and updating the source systems. Observe the postgres oltp database through pgAdmin and the minio bucket and the api endpoints through the browser.

#### Extraction Strategy Matrix
| Source | Protocol / Mechanism | Ingestion Mode | Bronze Target Path |
| :--- | :--- | :--- | :--- |
| **PostgreSQL OLTP** | SQL (`psycopg2` / `SQL Alchemy`) | **Master Snapshots** (`customers`, `products`, `sellers`) | `raw-bronze/postgres/snapshots/` |
| **PostgreSQL OLTP** | SQL (`psycopg2` / `SQL Alchemy`) | **Incremental Stream** (`orders`, `order_items`) | `raw-bronze/postgres/batches/` |
| **MinIO Drops** | S3 API (`boto3`) | **Cross-Bucket Sync** (`pay_review` drops) | `raw-bronze/external_s3/` |
| **Reference API** | HTTP REST (`requests`) | **Full Dump / Paginated Harvest** (`translation`, `geolocation`) | `raw-bronze/api/` |


![Data_source.png](https://raw.githubusercontent.com/bijay-0011/images/refs/heads/main/3.png)

### Minio s3 Bucket structure for Raw Layer
One thing about the data lake is that it is a single source of truth for all the data. The data lake is organized in a way that makes it easy to find and access the data you need. The raw layer is the first layer of the data lake, and it contains all the raw data that has been ingested from various sources. The raw layer is organized by source and ingestion strategy, which makes it easy to find the data you need.

To establish a unified data lake, all extracted data is stored in the **Raw Layer** of MinIO without any transformations, preserving the original schema and content. The data is organized by source and ingestion strategy as shown below:

```text
raw-bronze/
├── api/
│   ├── api_endpoint=geolocation/
│   └── api_endpoint=translations/
│
├── external_s3/
│   ├── stream_event=order_payments/
│   └── stream_event=order_reviews/
│
└── postgres/
    ├── batches/
    │   ├── table_name=orders/
    │   └── table_name=order_items/
    │
    └── snapshots/
        ├── table_name=customers/
        ├── table_name=products/
        └── table_name=sellers/
```

This source-oriented organization preserves data lineage, simplifies ingestion workflows, and provides a reliable foundation for downstream Bronze, Silver, and Gold data processing.

## Lets start extracting data and saving it in the data lake (Minio Bucket).

### Step 1: Environment Setup & Dependencies



#### 🟢 VS Code WSL Integration Guide
##### Quick Troubleshooting Steps
>If you are using **VS Code** on Windows and working with **WSL (Windows Subsystem for Linux)**, ensure that your environment is correctly configured >to avoid issues with virtual environments and kernel selection in Jupyter notebooks. You should see a green bottom-left icon in VS Code indicating >that you are running in WSL mode. If you see a blue/purple icon or no icon, you are running in standard Windows mode, which may cause issues with >virtual environments.
>1. **Quick Switch (Inside VS Code)**
>   * Press `Ctrl + Shift + P`(Devloper Option).
>   * Type `WSL: Reopen Folder in WSL`.
>   * Press `Enter`.
>
>2. **Install Required Extension**
>   * Press `Ctrl + Shift + X`(Extension).
>    * Search for `WSL` and install it.
>
>3. **Clear Broken Cache**
>   * Run `rm -rf ~/.vscode-server` in your Ubuntu terminal.
>   * Type `code .` again to launch.
>
#### **⚠️ Virtual Environment Not Showing in "Select Kernel"?**

> If your `uv` virtual environment does not appear in the **Select Kernel** list in VS Code (WSL Ubuntu/macOS), install the Jupyter kernel package inside your virtual environment and register it as a Jupyter kernel.
>
> ```bash
> uv pip install ipykernel
> ```
>
> Reload VS Code and check **Select Kernel** again. If the environment is still missing, register it manually:
>
> ```bash
> python -m ipykernel install --user \
>     --name=myenv \
>     --display-name="Python (myenv)"
> ```
>
> After running the commands:
>
> 1. Restart VS Code (or run **Developer: Reload Window**).
> 2. Open your notebook (`.ipynb`).
> 3. Click **Select Kernel** (top-right).
> 4. Choose **Python (.venv)**.
>
> If the kernel still does not appear, verify that VS Code has the **Python** and **Jupyter** extensions installed and that your WSL/macOS environment is being used.

In [1]:

# 1. Enable autoreload first
%load_ext autoreload
%autoreload 2

# Import necessary libraries
import os
import io
import boto3
from botocore.exceptions import ClientError

import sys
sys.path.append(os.path.dirname(os.getcwd()))  # Add the parent directory to the sys.path to import config_loader.py. Since the config_loader.py is in the parent directory, we need to add the parent directory to the sys.path so that Python can find it.
from config_loader import CONFIG # Make sure you can access CONFIG variable .

<span style="color: green; font-size: 25px;">Since we are trying to load our raw data from different source to the minio s3 bucket, we need to setup the communication with the minio.</span>



`boto3.client("s3", endpoint_url=..., aws_access_key_id=..., aws_secret_access_key=...)` creates a low-level client that lets you talk to any S3-compatible storage — including **MinIO** — using standard S3 API calls (list, upload, download, delete, etc.).

| Method | Syntax | Purpose |
|---|---|---|
| **List buckets** | `s3.list_buckets()` | Get all buckets available on the server |
| **Create bucket** | `s3.create_bucket(Bucket="name")` | Create a new bucket |
| **Delete bucket** | `s3.delete_bucket(Bucket="name")` | Delete an empty bucket |
| **Check bucket exists** | `s3.head_bucket(Bucket="name")` | Verify a bucket exists (raises error if not) |
| **List objects** | `s3.list_objects_v2(Bucket="name")` | List up to 1000 objects in a bucket |
| **List objects (folder view)** | `s3.list_objects_v2(Bucket="name", Prefix="path/", Delimiter="/")` | View "folders" (`CommonPrefixes`) and files at one level, like a directory listing |
| **Paginator** | `paginator = s3.get_paginator("list_objects_v2")`<br>`for page in paginator.paginate(Bucket="name"): ...` | Automatically loops through all pages of results — needed when a bucket has more than 1000 objects, since `list_objects_v2` alone only returns the first 1000 |
| **Check object exists / metadata** | `s3.head_object(Bucket="name", Key="key")` | Get metadata (size, type, last modified) without downloading |
| **Get object** | `s3.get_object(Bucket="name", Key="key")` | Read an object's content into memory (`["Body"].read()`) |
| **Download object** | `s3.download_file(Bucket, Key, local_path)` | Save an object directly to local disk |
| **Upload object (from file)** | `s3.upload_file(local_path, Bucket, Key)` | Upload a local file to the bucket |
| **Upload object (in-memory)** | `s3.put_object(Bucket="name", Key="key", Body=data)` | Upload raw bytes/string directly |
| **Delete object** | `s3.delete_object(Bucket="name", Key="key")` | Delete a single object |
| **Delete multiple objects** | `s3.delete_objects(Bucket="name", Delete={"Objects":[...]})` | Batch delete |
| **Copy object** | `s3.copy_object(Bucket, CopySource, Key)` | Copy/move an object within or across buckets |
| **Generate presigned URL** | `s3.generate_presigned_url("get_object", Params={...})` | Create a temporary shareable link to an object |

In [2]:
s3 = boto3.client(
    "s3",
    endpoint_url=CONFIG["storage"]["minio_endpoint"],
    aws_access_key_id=CONFIG["storage"]["minio_access_key"],
    aws_secret_access_key=CONFIG["storage"]["minio_secret_key"],
)
s3.list_buckets()["Buckets"] # Test the connection to MinIO

[{'Name': 'pay-review',
  'CreationDate': datetime.datetime(2026, 8, 6, 8, 31, 17, 49000, tzinfo=tzlocal())},
 {'Name': 'raw-bronze',
  'CreationDate': datetime.datetime(2026, 8, 12, 8, 23, 54, 145000, tzinfo=tzlocal())},
 {'Name': 'raw-data-lake',
  'CreationDate': datetime.datetime(2026, 8, 6, 7, 28, 10, 574000, tzinfo=tzlocal())}]

In [3]:
s3.list_objects_v2(Bucket="pay-review")["Contents"]# Test the connection to MinIO and list objects in the bucket

[{'Key': 'order_payments/batch_date=2026-08-06/batch_083200_835051.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 0, 843000, tzinfo=tzlocal()),
  'ETag': '"ddb3085e83d1799c680d57c75d71c2a1"',
  'Size': 3964,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083201_875471.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 1, 879000, tzinfo=tzlocal()),
  'ETag': '"7e4ef1b8ad04fbdab2433af4ad2bda0c"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083202_905932.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 2, 910000, tzinfo=tzlocal()),
  'ETag': '"550c443f06a643216910c3a3ef21cae6"',
  'Size': 3929,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083203_935790.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 3, 939000, tzinfo=tzlocal()),
  'ETag': '"2099e434df3d92a737b23c9fde928c3e"',
  'Size': 3898,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083204_967501.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 4, 971000, tzinfo=tzlocal()),
  'ETag': '"2075555dd60768520e527cd21f839f9d"',
  'Size': 4058,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083206_057305.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 6, 61000, tzinfo=tzlocal()),
  'ETag': '"404139fd6a1fbf7261e1a5261a7d5f57"',
  'Size': 3809,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083207_088550.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 7, 93000, tzinfo=tzlocal()),
  'ETag': '"2429de4dddd32c1d24c16953f353fa72"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083214_189879.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 14, 194000, tzinfo=tzlocal()),
  'ETag': '"0ed472b778b69cbce1b49c8e6f05e34d"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083215_221157.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 15, 227000, tzinfo=tzlocal()),
  'ETag': '"dc0d6670cd35177f93324fe6f2683f29"',
  'Size': 3964,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083216_252453.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 16, 257000, tzinfo=tzlocal()),
  'ETag': '"bf08cde9fe7f677447973959b004073d"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083217_344733.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 17, 348000, tzinfo=tzlocal()),
  'ETag': '"8a08d64b06b90be9c7d6b4e912f5b728"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083218_372031.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 18, 376000, tzinfo=tzlocal()),
  'ETag': '"89d140285879b03a6cbd647e54b7666c"',
  'Size': 3884,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083219_402172.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 19, 405000, tzinfo=tzlocal()),
  'ETag': '"35928d530bc18810c58ec759062222b9"',
  'Size': 3898,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083220_431895.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 20, 435000, tzinfo=tzlocal()),
  'ETag': '"adef8410cfe6a046dbadcc0aa0a8b6da"',
  'Size': 3892,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083221_461145.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 21, 465000, tzinfo=tzlocal()),
  'ETag': '"763f4d1676bdaaaedf6c58aa747ea1ef"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083222_488998.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 22, 493000, tzinfo=tzlocal()),
  'ETag': '"833cd4046a6f4010b18fb2fd413ae073"',
  'Size': 3882,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083223_517500.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 23, 521000, tzinfo=tzlocal()),
  'ETag': '"c2988046839cca07bd63fb7b60cde35b"',
  'Size': 3937,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083224_552027.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 24, 556000, tzinfo=tzlocal()),
  'ETag': '"d2de4987131f78eeb6eeb3b3c3cf5d65"',
  'Size': 3898,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083225_638540.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 25, 642000, tzinfo=tzlocal()),
  'ETag': '"73d269318b31e4c1932d0b590789cc0e"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083227_730483.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 27, 734000, tzinfo=tzlocal()),
  'ETag': '"073a6244db7f433a72e070255e0f93ed"',
  'Size': 3989,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083228_765348.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 28, 769000, tzinfo=tzlocal()),
  'ETag': '"d34c6924a7296097788a0b253774e8f3"',
  'Size': 3978,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083230_804140.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 30, 809000, tzinfo=tzlocal()),
  'ETag': '"9506a449fa2e83facebcf53ee3caac6e"',
  'Size': 3916,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083231_897268.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 31, 902000, tzinfo=tzlocal()),
  'ETag': '"683ca646bae3d687b4de919bc256ddc6"',
  'Size': 3947,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083235_938447.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 35, 946000, tzinfo=tzlocal()),
  'ETag': '"293ace40c423c0e7699fa8912b2dc3e5"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083236_974056.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 36, 981000, tzinfo=tzlocal()),
  'ETag': '"e5970d13d36ce3f53c066a1116a43089"',
  'Size': 3817,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083239_007306.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 39, 11000, tzinfo=tzlocal()),
  'ETag': '"b642d32f6801363e2f34826e0046da5b"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083240_039171.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 40, 43000, tzinfo=tzlocal()),
  'ETag': '"f75b2c6c4d1498d41400881eca4eb06d"',
  'Size': 3982,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083241_127619.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 41, 133000, tzinfo=tzlocal()),
  'ETag': '"1ee6e210864159115b950f20c0b16cc2"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083242_160183.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 42, 165000, tzinfo=tzlocal()),
  'ETag': '"70fe8c7f20b1935c5cb8d7530c8572af"',
  'Size': 4016,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083243_254590.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 43, 260000, tzinfo=tzlocal()),
  'ETag': '"a43de96e27c7419a68cb0411ff7ced6d"',
  'Size': 3939,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083244_285239.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 44, 290000, tzinfo=tzlocal()),
  'ETag': '"5f29bb52729250be49d5db53045e7cbb"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083245_381361.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 45, 386000, tzinfo=tzlocal()),
  'ETag': '"8e97b0caf167698273cb270287e9062d"',
  'Size': 4004,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083246_417336.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 46, 420000, tzinfo=tzlocal()),
  'ETag': '"2a2ee5bc08822d0cf6de7cea812b7093"',
  'Size': 3954,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083247_451854.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 47, 456000, tzinfo=tzlocal()),
  'ETag': '"b8098207d21abd0211126e7307e8960e"',
  'Size': 3979,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083248_540878.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 48, 545000, tzinfo=tzlocal()),
  'ETag': '"3c11dd1ce873f894b33b6276e4121fdd"',
  'Size': 3890,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083249_574816.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 49, 579000, tzinfo=tzlocal()),
  'ETag': '"6e47a5bc4cbda7b1456468a9573ba05e"',
  'Size': 4041,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083250_604385.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 50, 610000, tzinfo=tzlocal()),
  'ETag': '"f932fe870ad0db41a58af431752ed564"',
  'Size': 3943,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083252_642766.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 52, 648000, tzinfo=tzlocal()),
  'ETag': '"d113626b54b36340fe2e1241c1578785"',
  'Size': 3983,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083253_747038.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 53, 753000, tzinfo=tzlocal()),
  'ETag': '"d9482e743576116a9ed153ce5112de91"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083254_784828.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 32, 54, 790000, tzinfo=tzlocal()),
  'ETag': '"c67b806479c74f54cb44a3680f1e502d"',
  'Size': 3892,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083303_887637.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 3, 892000, tzinfo=tzlocal()),
  'ETag': '"cbb8916a3dbe5c66bb97054a2327a054"',
  'Size': 3943,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083304_917532.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 4, 922000, tzinfo=tzlocal()),
  'ETag': '"efd48ef608937886df195fe24aec2230"',
  'Size': 3985,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083306_017976.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 6, 24000, tzinfo=tzlocal()),
  'ETag': '"2d1c1b64d5659688d63335f9046a4b4c"',
  'Size': 4197,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083307_050393.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 7, 57000, tzinfo=tzlocal()),
  'ETag': '"48d71737c4e87fde5a304d78f0bdfb73"',
  'Size': 3943,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083308_092252.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 8, 95000, tzinfo=tzlocal()),
  'ETag': '"20bf6981251f75b4a295d66fb28b69b4"',
  'Size': 4111,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083309_121204.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 9, 127000, tzinfo=tzlocal()),
  'ETag': '"463f5a60ea91bd27c72e5121c2e8eb9b"',
  'Size': 3937,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083310_154271.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 10, 159000, tzinfo=tzlocal()),
  'ETag': '"5ab004019b6375115325fd6d1e7c7109"',
  'Size': 4048,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083311_187903.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 11, 196000, tzinfo=tzlocal()),
  'ETag': '"7c4ea2da55108aeb2ddab9ac65a63629"',
  'Size': 4180,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083312_292141.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 12, 295000, tzinfo=tzlocal()),
  'ETag': '"0df5d79107973920ca41589ad8c6d43f"',
  'Size': 4075,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083313_324966.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 13, 329000, tzinfo=tzlocal()),
  'ETag': '"d36fe05a83ca44caa2eadc9a58000062"',
  'Size': 3891,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083314_410930.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 14, 416000, tzinfo=tzlocal()),
  'ETag': '"6f6cf8bfc3eae1c854250ea43a5d3fce"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083315_446697.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 15, 452000, tzinfo=tzlocal()),
  'ETag': '"97e39668e7ede930c7bdc04b2168e7d6"',
  'Size': 4128,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083316_480493.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 16, 486000, tzinfo=tzlocal()),
  'ETag': '"1384db2aea4ffaab0647e76c3723f0a9"',
  'Size': 4083,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083317_579159.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 17, 582000, tzinfo=tzlocal()),
  'ETag': '"dd3e22e8d6de825ae68606c2b7344434"',
  'Size': 4136,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083318_701353.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 18, 704000, tzinfo=tzlocal()),
  'ETag': '"e75f0914e4d56d0a3e60e6d63b6cb537"',
  'Size': 3908,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083319_786087.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 19, 791000, tzinfo=tzlocal()),
  'ETag': '"d5647c39919681b5c79bbf6075dc6ae3"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083323_828219.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 23, 833000, tzinfo=tzlocal()),
  'ETag': '"fcb7d9c115eefc0a19b60ac3adfa5b1b"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083327_872421.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 27, 876000, tzinfo=tzlocal()),
  'ETag': '"08d7c62a76ea69cc96e32d75b9312759"',
  'Size': 3943,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083328_959477.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 28, 964000, tzinfo=tzlocal()),
  'ETag': '"7d7770b59054826d3fa449f7953b2b3d"',
  'Size': 3983,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083330_048112.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 30, 52000, tzinfo=tzlocal()),
  'ETag': '"b1509c7192e7f57cbf88db4757610d61"',
  'Size': 4023,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083331_140454.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 31, 145000, tzinfo=tzlocal()),
  'ETag': '"2341c7c2fe2ab9ccd27608190a95d05b"',
  'Size': 4087,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083332_173376.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 32, 177000, tzinfo=tzlocal()),
  'ETag': '"9d77c4b4a7999070485dbcf1401aa368"',
  'Size': 4034,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083333_267434.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 33, 273000, tzinfo=tzlocal()),
  'ETag': '"7b5b5f9b76b68ef6f80538aa878c4913"',
  'Size': 3983,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083334_297803.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 34, 301000, tzinfo=tzlocal()),
  'ETag': '"88cfa125caadd8b5ec225fb7ce5fcc6e"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083335_330956.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 35, 335000, tzinfo=tzlocal()),
  'ETag': '"be788fd374ab9da58c4f354da85b5dfe"',
  'Size': 4033,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083336_419589.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 36, 425000, tzinfo=tzlocal()),
  'ETag': '"239acb8a2fb72bc6357b5bd681068c55"',
  'Size': 3996,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083337_519720.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 37, 523000, tzinfo=tzlocal()),
  'ETag': '"4180cb3a988e53dc8ebf39551a2e1b95"',
  'Size': 3897,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083338_612500.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 38, 616000, tzinfo=tzlocal()),
  'ETag': '"a7ee4cddea61453b80f4469fced9f6e3"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083339_700488.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 39, 705000, tzinfo=tzlocal()),
  'ETag': '"df2e7db9e85013be918acf7bb5eab526"',
  'Size': 3846,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083340_734189.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 40, 738000, tzinfo=tzlocal()),
  'ETag': '"813339d6ad5cd464be7d7eea7575ea09"',
  'Size': 3937,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083341_822273.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 41, 827000, tzinfo=tzlocal()),
  'ETag': '"0bfee25be4d6cb982035cc2f8aa106b4"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083352_014135.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 52, 19000, tzinfo=tzlocal()),
  'ETag': '"47ad7a9ac4e845666a814dea7d23c971"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083353_105505.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 53, 112000, tzinfo=tzlocal()),
  'ETag': '"d019f061f72b26f685a0d4d02fa9ee7f"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083354_200178.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 54, 204000, tzinfo=tzlocal()),
  'ETag': '"09813d77680baa9fc2ea96653d938073"',
  'Size': 3789,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083355_232686.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 55, 239000, tzinfo=tzlocal()),
  'ETag': '"ce0486067f4626227b276789a33fb308"',
  'Size': 3908,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083356_329488.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 56, 335000, tzinfo=tzlocal()),
  'ETag': '"47fa45b667471dd46d4b1fbb36fba899"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083357_424392.parquet',
  'LastModified': datetime.datetime(2026, 8, 6, 8, 33, 57, 429000, tzinfo=tzlocal()),
  'ETag': '"9c4900fd0746caea8dc168e67392c114"',
  'Size': 3764,
  'StorageClass': 'STANDARD'},
 {'Key': 'order_payments/batch_date=2026-08-06/batch_083358_457923.parquet',

Here, we need to check if our destination bucket(Data Lake Bucket) exists in the minio s3. If it does not exist, we will create it.

In [4]:
def ensure_bucket_exists(bucket_name):
    """
    Ensure that the specified bucket exists in MinIO. If it does not exist, create it.

    Args:
        bucket_name (str): The name of the bucket to check or create.
    """
    try:
        # Check if the bucket exists
        # your code here 
        s3.head_bucket(Bucket=bucket_name)
        print(f"Bucket '{bucket_name}' already exists.")
    except ClientError as e:
        error_code = e.response['Error']['Code']
        if error_code == '404' or error_code == 'NoSuchBucket':
            # Bucket does not exist, create it
            # your code Here
            s3.create_bucket(Bucket=bucket_name)
            print(f"Bucket '{bucket_name}' created successfully.")
        else:
            # Some other error occurred
            print(f"Error checking/creating bucket '{bucket_name}': {e}")
ensure_bucket_exists(CONFIG["storage"]["bronze_bucket"])  # Check if the bucket exists, and create it if it doesn't

Bucket 'raw-bronze' already exists.

##### **This bucket checking and creation logic should be execute before we extract data from source and save it in the data lake (Minio Bucket) for every source. So , let's create a python script that will check if the bucket exists and create it if it does not exist. Since this script will be used before every extraction, we can create a **BaseExtractor** class that will have this logic. Also we have minio ui for basic checkup so we rarely use this class alone so it is better to create a abstract base class for this purpose. The other extractors will inherit from this class and implement their own extraction logic.**

There is already a `base_extractor.py` file in the `extractor` folder that contains the `BaseExtractor` class with the wrapper code. Implement this logic in the `BaseExtractor` class.

In [5]:
# After defining the `BaseExtractor` class. lets check it..
from base_extractor import BaseExtractor
# Since it is a abstract class, we cannot create its object 
class TestExtractor(BaseExtractor):
    
    def run(self):
        print("Dummy run() executed")

extractor = TestExtractor()

2026-08-20 07:42:01 [INFO] base_extractor: Bucket 'raw-bronze' already exists.

### Step 2: Exploring the PostgreSQL OLTP Source

Before we write code to extract the data, we need to understand what we are dealing with. Our e-commerce platform uses a PostgreSQL database as its primary OLTP (Online Transaction Processing) system. 

**Open pgAdmin** and connect to the `postgres_oltp` database. 

Try running these basic SQL queries in the pgAdmin Query Tool to explore the schema and data:

```sql
-- 1. Check the structure of a table (e.g., orders)
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'orders';

-- 2. Preview reference data (Snapshot candidates)
SELECT * FROM customers LIMIT 10;
SELECT * FROM products LIMIT 10;

-- 3. Check the volume of our transactional data
SELECT COUNT(*) FROM orders;

#### Observe the Data Simulation in Action

To simulate a real-world e-commerce environment, ensure your background simulation is running. 

Once the simulation is active, run the following query in pgAdmin multiple times, pausing for a few seconds between runs:

```sql
SELECT * FROM orders ORDER BY order_purchase_timestamp DESC LIMIT 5;

#### Connecting to PostgreSQL with SQLAlchemy

To extract this data programmatically, we will use **SQLAlchemy**. SQLAlchemy is a Python SQL toolkit that allows us to communicate directly with the database inside the `postgres_oltp` container—doing exactly what pgAdmin does, but through Python.

To connect, SQLAlchemy requires a **Database URL** formatted like this:
`postgresql://<username>:<password>@<host>:<port>/<database_name>`

Let's construct our engine using the credentials from our `CONFIG` loader, connect to the database, and execute a basic query to ensure our Python environment can read the data.

#### Essential SQLAlchemy & Pandas Integration Cheat Sheet

Here are the most useful and necessary functions and syntax for connecting to, querying, and managing databases with SQLAlchemy, especially when working with Pandas.

| Category | Function / Syntax | Key Arguments | Brief Explanation |
| :--- | :--- | :--- | :--- |
| **Connection & Setup** | `create_engine(url, ...)` | `url`: DB connection string.<br>`echo`: `bool` (logs SQL).<br>`pool_size`: `int` (conn pool size). | Creates the engine that manages connections and acts as the central hub for the database. |
| **Connection & Setup** | `engine.connect()` | None. | Opens an active connection. Best used within a context manager (`with engine.connect() as conn:`) for auto-closing. |
| **Executing Queries** | `text(sql_string)` | `sql_string`: A raw SQL query string. | Wraps a raw SQL string into an executable object. Essential for safe, parameterized queries. |
| **Executing Queries** | `connection.execute(stmt)` | `stmt`: A `text()` object.<br>`parameters`: `dict` of variables. | Executes the SQL command and returns a `CursorResult` object containing the fetched rows. |
| **Executing Queries** | `result.fetchall()`<br>`result.fetchone()` | None. | Methods on `CursorResult`. `fetchall()` returns all rows as a list; `fetchone()` retrieves just the next row. |
| **Database Metadata** | `inspect(engine)` | `subject`: The database engine. | Creates an `Inspector` object used to explore database metadata (tables, columns) without writing SQL. |
| **Database Metadata** | `inspector.get_table_names()` | `schema`: `str` (Optional schema name, e.g., 'public'). | Returns a list of strings representing all table names in the database. Ideal for automated extraction loops. |
| **Pandas Integration** | `pd.read_sql(sql, con)` | `sql`: SQL string or `text()`.<br>`con`: SQLAlchemy engine/connection. | Executes a query and directly loads the result set into a Pandas DataFrame for data manipulation. |
| **Pandas Integration** | `df.to_sql(name, con)` | `name`: Target table name.<br>`con`: SQLAlchemy engine.<br>`if_exists`: `'fail'`, `'replace'`, `'append'`. | Writes records directly from a Pandas DataFrame back into a SQL database table. |

In [6]:
# Import the necessary libraries for database connection
import pandas as pd
from datetime import datetime
import json
from pprint import pprint
from sqlalchemy import create_engine, inspect, text

# Loading the necessary configuration variables
CONFIG["database"]["oltp"]

{'host': 'localhost',
 'port': '5432',
 'name': 'oltp_db',
 'user': 'your_user_name',
 'password': 'your_postgres_password',
 'oltp_url': 'postgresql+psycopg2://your_user_name:your_postgres_password@localhost:5432/oltp_db'}

In [7]:
engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])

 Exploring the Database Programmatically
 
Before we build our automated extractor, let's use the SQLAlchemy tools to learn about to explore the database directly from Python. We will use the `inspect` module to check the schema, and `Pandas` to sample the data.

In [8]:
# 2. Use the Inspector to discover what tables exist
inspector = inspect(engine)
tables = inspector.get_table_names()

print("Tables found in the PostgreSQL Database:")
print(tables)

Tables found in the PostgreSQL Database:
['system_health_check', 'customers', 'orders', 'order_items', 'products', 'sellers']

Llet's look at the structure of the `orders` table. This is critical for understanding which columns we can use for incremental extraction (like timestamps).

In [9]:
# 3. Inspect the columns of a specific table
print("Schema for the 'orders' table:")
columns = inspector.get_columns('order_items')
# Format the output into a clean dataframe for readability
schema_df = pd.DataFrame(columns)[['name', 'type', 'nullable']]
display(schema_df)

# Primary Key
primary_key = inspector.get_pk_constraint('order_items')
pprint(primary_key.get('constrained_columns'))

# Foregin Key
foreign_key = inspector.get_foreign_keys('order_items')
print("Foregin Key")
if foreign_key:
    for fk in foreign_key:
        print(f" - Constraint: {fk.get('name')}")
        print(f"   Local Column(s): {fk.get('constrained_columns')}")
        print(f"   Refers to Table: '{fk.get('referred_table')}' on Column(s): {fk.get('referred_columns')}\n")
else:
    print(" - No foreign keys found.")

Schema for the 'orders' table:

                  name            type  nullable
0             order_id     VARCHAR(50)     False
1        order_item_id         INTEGER     False
2           product_id     VARCHAR(50)     False
3            seller_id     VARCHAR(50)     False
4  shipping_limit_date       TIMESTAMP      True
5                price  NUMERIC(10, 2)     False
6        freight_value  NUMERIC(10, 2)     False

['order_id', 'order_item_id']
Foregin Key
 - Constraint: fk_order_items_orders
   Local Column(s): ['order_id']
   Refers to Table: 'orders' on Column(s): ['order_id']

 - Constraint: fk_order_items_products
   Local Column(s): ['product_id']
   Refers to Table: 'products' on Column(s): ['product_id']

 - Constraint: fk_order_items_sellers
   Local Column(s): ['seller_id']
   Refers to Table: 'sellers' on Column(s): ['seller_id']

#### Let's execute some queries

### `pd.read_sql` vs. `conn.execute`: Which should you use?

Both methods execute SQL, but they serve completely different purposes in a data pipeline. 

| Feature | `pd.read_sql(query, engine)` | `conn.execute(query)` |
| :--- | :--- | :--- |
| **Output Type** | Pandas DataFrame | SQLAlchemy `CursorResult` (iterable rows) |
| **Primary Use Case** | **Data Extraction:** Fetching data to manipulate, analyze, or save to disk (e.g., Parquet/CSV). | **Execution & Admin:** Running DML (INSERT, UPDATE, DELETE) or DDL (CREATE, DROP) commands. |
| **Memory Usage** | High. Loads the entire result set into memory at once (unless using the `chunksize` parameter). | Low. Can stream results row-by-row, making it highly memory efficient. |
| **Convenience** | High. Automatically handles column names, data types, and tabular formatting. | Low. Requires manual looping and parsing to format the data. |

#### 💡 Best Practice for Data Engineers:
*   **Use `pd.read_sql`** when extracting data from your source database that you intend to transform or load into your Data Lake.
*   **Use `conn.execute`** when you need to trigger a database procedure, update tracking tables, delete old records, or fetch massive datasets row-by-row where a DataFrame would crash your system's RAM.

In [10]:
for col in inspector.get_columns('orders'):
    print(col.get('name'))

order_id
customer_id
order_status
order_purchase_timestamp
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
order_estimated_delivery_date

In [11]:
test_query = text('SELECT * FROM orders LIMIT 10;')
with engine.connect() as conn:
    result = conn.execute(test_query)
    for row in result:
        print(row)
        # print(f"order_id:{row.order_id}, order_approved_at: {row.order_approved_at}")

('2e7a8482f6fb09756ca50c10d7bfc047', '08c5351a6aca1c1589a38f244edeee9d', 'shipped', datetime.datetime(2016, 9, 4, 21, 15, 19), datetime.datetime(2016, 10, 7, 13, 18, 3), datetime.datetime(2016, 10, 18, 13, 14, 51), None, datetime.datetime(2016, 10, 20, 0, 0))
('e5fa5a7210941f7d56d0208e4e071d35', '683c54fc24d40ee9f8a6fc179fd9856c', 'canceled', datetime.datetime(2016, 9, 5, 0, 15, 34), datetime.datetime(2016, 10, 7, 13, 17, 15), None, None, datetime.datetime(2016, 10, 28, 0, 0))
('809a282bbd5dbcabb6f2f724fca862ec', '622e13439d6b5a0b486c435618b2679e', 'canceled', datetime.datetime(2016, 9, 13, 15, 24, 19), datetime.datetime(2016, 10, 7, 13, 16, 46), None, None, datetime.datetime(2016, 9, 30, 0, 0))
('bfbd0f9bdef84302105ad712db648a6c', '86dc2ffce2dfff336de2f386a786e574', 'delivered', datetime.datetime(2016, 9, 15, 12, 16, 38), datetime.datetime(2016, 9, 15, 12, 16, 38), datetime.datetime(2016, 11, 7, 17, 11, 53), datetime.datetime(2016, 11, 9, 7, 47, 38), datetime.datetime(2016, 10, 4, 0, 0))
('71303d7e93b399f5bcd537d124c0bcfa', 'b106b360fe2ef8849fbbd056f777b4d5', 'canceled', datetime.datetime(2016, 10, 2, 22, 7, 52), datetime.datetime(2016, 10, 6, 15, 50, 56), None, None, datetime.datetime(2016, 10, 25, 0, 0))
('3b697a20d9e427646d92567910af6d57', '355077684019f7f60a031656bd7262b8', 'delivered', datetime.datetime(2016, 10, 3, 9, 44, 50), datetime.datetime(2016, 10, 6, 15, 50, 54), datetime.datetime(2016, 10, 23, 14, 2, 13), datetime.datetime(2016, 10, 26, 14, 2, 13), datetime.datetime(2016, 10, 27, 0, 0))
('be5bc2f0da14d8071e2d45451ad119d9', '7ec40b22510fdbea1b08921dd39e63d8', 'delivered', datetime.datetime(2016, 10, 3, 16, 56, 50), datetime.datetime(2016, 10, 6, 16, 3, 44), datetime.datetime(2016, 10, 21, 16, 33, 46), datetime.datetime(2016, 10, 27, 18, 19, 38), datetime.datetime(2016, 11, 7, 0, 0))
('65d1e226dfaeb8cdc42f665422522d14', '70fc57eeae292675927697fe03ad3ff5', 'canceled', datetime.datetime(2016, 10, 3, 21, 1, 41), datetime.datetime(2016, 10, 4, 10, 18, 57), datetime.datetime(2016, 10, 25, 12, 14, 28), datetime.datetime(2016, 11, 8, 10, 58, 34), datetime.datetime(2016, 11, 25, 0, 0))
('a41c8759fbe7aab36ea07e038b2d4465', '6f989332712d3222b6571b1cf5b835ce', 'delivered', datetime.datetime(2016, 10, 3, 21, 13, 36), datetime.datetime(2016, 10, 5, 3, 11, 49), datetime.datetime(2016, 10, 25, 11, 57, 59), datetime.datetime(2016, 11, 3, 10, 58, 7), datetime.datetime(2016, 11, 29, 0, 0))
('d207cc272675637bfed0062edffd0818', 'b8cf418e97ae795672d326288dfab7a7', 'delivered', datetime.datetime(2016, 10, 3, 22, 6, 3), datetime.datetime(2016, 10, 4, 10, 28, 7), datetime.datetime(2016, 10, 21, 14, 23, 37), datetime.datetime(2016, 10, 31, 11, 7, 42), datetime.datetime(2016, 11, 23, 0, 0))

In [12]:
# Using pandas .read_sql
tables = inspector.get_table_names()
count = {}

for table in tables:
    res = pd.read_sql(f"SELECT COUNT(*) FROM {table}",con=engine)
    count[table] = int(res["count"].iloc[0])
pprint(count)

{'customers': 99441,
 'order_items': 3186,
 'orders': 2830,
 'products': 32951,
 'sellers': 3095,
 'system_health_check': 3}

In [13]:
for table_name in tables:
    # We use parameterized queries for safety and best practices, even for simple counts
    query = text(f"SELECT COUNT(*) as total_rows FROM {table_name}")
    with engine.connect() as conn:
        result = conn.execute(query).scalar() # .scalar() returns just the single value
        print(f"{table_name} : {result} rows")

system_health_check : 3 rows
customers : 99441 rows
orders : 2830 rows
order_items : 3186 rows
products : 32951 rows
sellers : 3095 rows

##### The Safe** Way to Execute Queries: Preventing SQL Injection

When building data pipelines, you will often need to pass dynamic values into your SQL queries—for example, fetching records added after a specific timestamp, or filtering by a specific category.

**The Golden Rule:** *Never* use Python's built-in string formatting (like f-strings or `.format()`) to insert variables directly into a SQL string. This leaves your database vulnerable to SQL injection attacks and can break your queries if strings contain special characters (like quotes).

The safe way in SQLAlchemy involves two steps:
1. Wrap your raw SQL in the `text()` function.
2. Use **bind parameters** by placing a colon `:` before a variable name in your SQL string, and then pass the actual values as a dictionary when executing.

> **Key Insight:** When you use bind parameters (`:target_date`), SQLAlchemy and the underlying database driver (like `psycopg2`) automatically handle escaping quotes and sanitizing the input before it ever touches the database engine.

In [14]:
# 1. Define the query using named bind parameters (notice the :target_date)
safe_query = text("""
    SELECT order_id, order_purchase_timestamp, order_status 
    FROM orders 
    WHERE order_purchase_timestamp > :target_date 
    LIMIT 5;
""")
query_params = {"target_date": "2016-08-01 00:00:00"}

with engine.connect() as conn:
    result = conn.execute(safe_query, query_params)
    for row in result:
        print(row)

('2e7a8482f6fb09756ca50c10d7bfc047', datetime.datetime(2016, 9, 4, 21, 15, 19), 'shipped')
('e5fa5a7210941f7d56d0208e4e071d35', datetime.datetime(2016, 9, 5, 0, 15, 34), 'canceled')
('809a282bbd5dbcabb6f2f724fca862ec', datetime.datetime(2016, 9, 13, 15, 24, 19), 'canceled')
('bfbd0f9bdef84302105ad712db648a6c', datetime.datetime(2016, 9, 15, 12, 16, 38), 'delivered')
('71303d7e93b399f5bcd537d124c0bcfa', datetime.datetime(2016, 10, 2, 22, 7, 52), 'canceled')

In [15]:
# Example using Pandas (The standard for data engineering pipelines)
df_safe = pd.read_sql(
    safe_query, 
    con=engine, 
    params=query_params  # Pass the dictionary safely here!
)
display(df_safe)

                           order_id order_purchase_timestamp order_status
0  2e7a8482f6fb09756ca50c10d7bfc047      2016-09-04 21:15:19      shipped
1  e5fa5a7210941f7d56d0208e4e071d35      2016-09-05 00:15:34     canceled
2  809a282bbd5dbcabb6f2f724fca862ec      2016-09-13 15:24:19     canceled
3  bfbd0f9bdef84302105ad712db648a6c      2016-09-15 12:16:38    delivered
4  71303d7e93b399f5bcd537d124c0bcfa      2016-10-02 22:07:52     canceled

### Step 3: The Extraction Strategy (Static vs. Dynamic Data)

Before we look at the full automated pipeline code, we need a clear vision of **what** we are extracting and **how**. In our database, tables generally fall into two categories, requiring two distinct extraction strategies:

#### 1. Static / Master Data (Snapshots)
*   **Tables:** `customers`, `products`, `sellers`
*   **Behavior:** These tables update infrequently. Records are modified, but massive volumes of new data aren't added every second.
*   **Strategy:** **Full Snapshots.** We extract the entire table. To avoid doing this unnecessarily, our code will use PostgreSQL's hidden system column `xmin` (transaction ID). If the maximum `xmin` hasn't changed since our last run, it means no inserts, updates, or deletes occurred, and we can safely skip the extraction!

#### 2. Dynamic / Transactional Data (Incremental Batches)
*   **Tables:** `orders`, `order_items`
*   **Behavior:** High velocity. New transactions are appended constantly. 
*   **Strategy:** **Incremental Watermarking.** Extracting the whole table every time would crash our system. Instead, we track the maximum `order_purchase_timestamp` from the last run (our "watermark") and only query rows *greater* than that timestamp.

In [16]:
tables_to_snapshot = ["customers", "sellers", "products"]
schema = "public"
engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])

In [17]:
# Let's test for sellers table
df_sellers = pd.read_sql(
    text("SELECT * FROM public.sellers LIMIT 50;"),
    con=engine
)
display(df_sellers.head(10))

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
5,c240c4061717ac1806ae6ee72be3533b,20920,rio de janeiro,RJ
6,e49c26c3edfa46d227d5121a6b6e4d37,55325,brejao,PE
7,1b938a7ec6ac5061a66a3766e0e75f90,16304,penapolis,SP
8,768a86e36ad6aae3d03ee3c6433d61df,1529,sao paulo,SP
9,ccc4bbb5f32a6ab2b7066a4130f114e3,80310,curitiba,PR

#### In-Memory Parquet Conversion & Hive-Style Partitioning

Now that we have our data in a Pandas DataFrame, we need to move it to our MinIO Data Lake. 

**Why Parquet?** 
Parquet is a columnar storage format. It compresses data heavily and is optimized for analytical queries (OLAP), making it the gold standard for Data Lakes.

**Why In-Memory?**
Writing a CSV or Parquet file to the local hard drive first is slow and creates clutter. Instead, we use Python's `io.BytesIO()` to hold the file purely in RAM as a stream of bytes, which we then send directly over the network to MinIO.

**Our Partitioning Style (Hive-Style)**
We will organize our files in S3 using **Hive-style partitioning** (e.g., `folder/key=value/`). This allows query engines (like Trino, Spark, or DuckDB) to prune directories they don't need to read.
*   *Snapshot Path:* `postgres/snapshots/table_name=customers/snapshot_date=2026-08-04/snapshot_114220.parquet`
*   *Incremental Path:* `postgres/batches/table_name=orders/batch_date=2026-08-04/batch_114220.parquet`

Let's test the Parquet conversion and upload process:

In [18]:
# Parquet Conversion & S3 Upload ---
# 1. Create an in-memory bytes buffer
buffer = io.BytesIO()

# 2. Write the DataFrame to the buffer as a Parquet file
# We use the 'pyarrow' engine, which is the standard for Parquet in Python
df_sellers.to_parquet(buffer, index=False, engine="pyarrow")

# 3. Reset the buffer's "cursor" back to the beginning (0) so boto3 can read it from the start
buffer.seek(0)

0

In [19]:
# 4. Generate our Hive-partitioned S3 Key (File path)
now = datetime.now()
table_name = "sellers"
bronze_bucket = CONFIG["storage"]["bronze_bucket"]
snapshot_date = now.strftime("%Y-%m-%d")
snapshot_time = now.strftime("%H%M%S") # e.g., 114220

s3_key = f"postgres/test/table_name={table_name}/snapshot_date={snapshot_date}/snapshot_{snapshot_time}.parquet"
# s3 = boto3.client(
#     "s3",
#     endpoint_url=CONFIG["storage"]["minio_endpoint"],
#     aws_access_key_id=CONFIG["storage"]["minio_access_key"],
#     aws_secret_access_key=CONFIG["storage"]["minio_secret_key"],
# )
print(f"Uploading to bucket: {bronze_bucket}")
print(f"Target Path: {s3_key}")
s3.upload_fileobj(buffer, bronze_bucket, s3_key)
print("Upload Complete! Check your MinIO console.")

Uploading to bucket: raw-bronze
Target Path: postgres/test/table_name=sellers/snapshot_date=2026-08-20/snapshot_074202.parquet
Upload Complete! Check your MinIO console.

##### Understanding S3 Upload Methods in `boto3`

In the previous cell, we used `upload_fileobj` to send our Parquet file to MinIO, but when updating our state metadata (like the watermark JSON), we will use `put_object`. 

Why? The `boto3` library provides three primary ways to upload data to an S3-compatible bucket, each designed for a specific scenario:

| Upload Method | Source Data Type | Handles Multipart (Large Files)? | Best Use Case in Data Engineering |
| :--- | :--- | :--- | :--- |
| `put_object()` | Raw Strings or Bytes | ❌ No (Single PUT request) | Small payloads like metadata, JSON state files, or tiny configuration text. |
| `upload_fileobj()` | File-like object (e.g., `io.BytesIO()`) | ✅ Yes (Automatic) | **In-memory data pipelines.** Uploading Pandas DataFrames converted to Parquet/CSV in RAM, without touching the local hard drive. |
| `upload_file()` | Local File Path (e.g., `'/tmp/data.csv'`) | ✅ Yes (Automatic) | Uploading large log files or database dumps that already exist physically on your local disk. |

#### 💡 How Multipart Upload Works (and why it matters)
For both `upload_file` and `upload_fileobj`, `boto3` automatically checks the size of the data. If the data is large (typically > 8MB), it splits the file into chunks, uploads them concurrently in parallel threads, and reassembles them in S3. `put_object` does *not* do this, which is why it should only be used for very small strings or configuration files.

In [20]:
import pandas as pd
from datetime import datetime
from sqlalchemy import create_engine

def upload_static_tables_v1(tables_to_snapshot: list = None):
    """
    Uploads specified tables from the PostgreSQL database to MinIO in Parquet format.

    Args:
        tables_to_snapshot (list): List of table names to snapshot. If None, defaults to ["customers", "sellers", "products"].
    """
    if tables_to_snapshot is None:
        tables_to_snapshot = ["customers", "sellers", "products"]

    schema = CONFIG["postgres"]["schema"]
    pg_conf = CONFIG["postgres"]
    engine = create_engine(
        f"postgresql+psycopg2://{pg_conf['user']}:{pg_conf['password']}"
        f"@{pg_conf['host']}:{pg_conf['port']}/{pg_conf['database']}"
    )
    bronze_bucket = CONFIG["storage"]["bronze_bucket"]

    for table_name in tables_to_snapshot:
        # Fetch data from the table
        query = f'SELECT * FROM {schema}.{table_name}'
        df = pd.read_sql(query, engine)

        # Create an in-memory bytes buffer
        buffer = io.BytesIO()

        # Write the DataFrame to the buffer as a Parquet file
        df.to_parquet(buffer, engine="pyarrow", index=False)

        # Reset the buffer's cursor back to the beginning
        buffer.seek(0)

        # Generate Hive-partitioned S3 Key (File path)
        now = datetime.now()
        snapshot_date = now.strftime("%Y-%m-%d")
        snapshot_time = now.strftime("%H%M%S")  # e.g., 114220

        s3_key = f"postgres/snapshots/table_name={table_name}/snapshot_date={snapshot_date}/snapshot_{snapshot_time}.parquet"

        print(f"Uploading {table_name} to bucket: {bronze_bucket}")
        print(f"Target Path: {s3_key}")

        # Upload to MinIO
        s3.put_object(
            Bucket=bronze_bucket,
            Key=s3_key,
            Body=buffer.getvalue(),
        )

        print(f"Upload of {table_name} Complete! Check your MinIO console.")

In [21]:
print(CONFIG.keys())

dict_keys(['simulation', 'database', 'pgadmin', 'api', 'storage'])

### Step 4: Optimizing Snapshots with PostgreSQL `xmin`

We know how to extract a full table and upload it to MinIO. But what if we schedule this script to run every 15 minutes, and no new customers were added? 

**The Inefficiency of Naive Extraction:**
If a table has 1 million rows, pulling all 1 million rows across the network, converting them to Parquet in RAM, and storing a new duplicate file in MinIO every 15 minutes is a massive waste of:
1. **Database I/O:** Slows down the production OLTP database.
2. **Compute & RAM:** Your Python worker works unnecessarily hard.
3. **Storage:** Clutters your Data Lake with identical duplicate snapshots.

**The Solution: State Tracking**
We need a way to ask the database: *"Has anything changed since the last time I checked?"*

If the data remains unchanged, we should **skip the extraction entirely**. For our static/master tables (`customers`, `products`, `sellers`), we will use a hidden PostgreSQL feature called `xmin`. Because this table doesnot contain any uniq and incrimental timestamp column.

#### What is `xmin`?
PostgreSQL uses a system called MVCC (Multi-Version Concurrency Control) to handle transactions. Because of this, every row in a PostgreSQL table has a hidden system column named `xmin`. 
*   `xmin` records the **Transaction ID** of the transaction that inserted the row.
*   When a row is **updated**, PostgreSQL actually deletes the old row and inserts a new one, assigning it a brand new, higher `xmin`.

By checking the **Maximum `xmin`** in a table, we can instantly know if any inserts or updates have occurred!

> PostgreSQL uses hidden system columns for transaction tracking—xmin records row creations/updates while xmax records deletions/locks—making MAX(xmin) a fast, zero-overhead way to detect 100% of data changes in pipelines without physical hard deletes.

In [22]:
# Lets take example on customers

table_name = "sellers"
print(f"Checking for changes in the '{table_name}' table...")

# 1. Query the database for the current highest xmin
# Note: xmin is a special internal type, so we cast it to text, then bigint for Python compatibility
xmin_query = text(f"SELECT COALESCE(MAX(xmin::text::bigint), 0) FROM public.{table_name}")
with engine.connect() as conn:
    current_max_xmin = conn.execute(xmin_query).scalar()
print(f"Current Max xmin in Database: {current_max_xmin}")

Checking for changes in the 'sellers' table...
Current Max xmin in Database: 753

State Management with Metadata Files

To make our change-detection mechanism work across multiple pipeline executions, our code needs to "remember" the highest `xmin` it processed during its last run. 

Since our data pipeline is stateless, we will store this state directly in our MinIO Data Lake inside a dedicated metadata folder:

$$\text{\texttt{s3://raw-bronze/metadata/table\_name=\{table\_name\}/state.json}}$$

Every time a snapshot completes, we save a lightweight `state.json` file structured like this:

```json
{
  "table": "customers",
  "last_xmin": 105423,
  "updated_at": "2026-08-04T12:00:00"
}

##### Let's create the logic to create a state.json file and put it in our bucket

In [23]:
table = "test_table"
state_key = f"metadata/table_name={table}/state.json"
bronze_bucket = CONFIG["storage"]["bronze_bucket"]

payload = json.dumps({
    "table": table_name,
    "last_xmin": current_max_xmin,
    "updated_at":datetime.now().isoformat()
})
s3.put_object(
    Bucket=bronze_bucket,
    Key=state_key,
    Body=payload.encode('utf8'),
    ContentType="applicatio/json",
)

# print(payload)

{'ResponseMetadata': {'RequestId': '18CD7397CBE49DD6',
  'HostId': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'accept-ranges': 'bytes',
   'content-length': '0',
   'etag': '"403478a5dfc59537cbbc1ccfa67583de"',
   'server': 'MinIO',
   'strict-transport-security': 'max-age=31536000; includeSubDomains',
   'vary': 'Origin, Accept-Encoding',
   'x-amz-checksum-crc32': 'sMlFvg==',
   'x-amz-checksum-type': 'FULL_OBJECT',
   'x-amz-id-2': 'dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8',
   'x-amz-request-id': '18CD7397CBE49DD6',
   'x-content-type-options': 'nosniff',
   'x-ratelimit-limit': '1219',
   'x-ratelimit-remaining': '1219',
   'x-xss-protection': '1; mode=block',
   'date': 'Thu, 20 Aug 2026 07:42:02 GMT'},
  'RetryAttempts': 0},
 'ETag': '"403478a5dfc59537cbbc1ccfa67583de"',
 'ChecksumCRC32': 'sMlFvg==',
 'ChecksumType': 'FULL_OBJECT'}

#### While re-running the extractor code for static tables, we need to check if there is any insert or update occur in that particular table by using xmin value. If xmin  of the table is unchanged we can completly skip the extractor part. 
Here we need to read the state.json save in our metadata for our table...

In [24]:
# key = f"metadata/table_name=test_tabl/states.json"

try:
    response = s3.get_object(Bucket=bronze_bucket, Key = state_key)
    content = json.loads(response["Body"].read().decode("utf8"))
    print(f"Last xmin Value: {content.get("last_xmin")}")
except ClientError as e:
    if e.response.get('Error').get('Code') == 'NoSuchKey':
        print(f"No previous state found for '{table_name}'")
    raise e

Last xmin Value: 753

#### Let's put our metadata state logic formally

In [25]:
import json
from datetime import datetime, timezone
from botocore.exceptions import ClientError
table = "customers"
state_key = f"metadata/table_name={table}/state.json"
bronze_bucket = CONFIG["storage"]["bronze_bucket"]


# 1. Function to fetch stored xmin state from MinIO
def get_last_synced_xmin(table_name):
    key = f"metadata/table_name={table_name}/state.json"
    try:
        response = s3.get_object(Bucket=bronze_bucket, Key=key)
        state_data = json.loads(response["Body"].read())
        return state_data.get("last_xmin", 0)
    except ClientError as e:
        if e.response["Error"]["Code"] == "NoSuchKey":
            print(f"No previous state found for '{table_name}'. Defaulting last_xmin to 0.")
            return 0  # First run
        raise e


# 2. Function to update stored xmin state in MinIO using put_object
def update_synced_xmin(table_name, new_xmin):
    key = f"metadata/table_name={table_name}/state.json"
    payload = json.dumps({
        "table_name": table_name,
        "last_xmin": new_xmin,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    })

    s3.put_object(
        Bucket=bronze_bucket,
        Key=key,
        Body=payload,
        ContentType="application/json",
    )
    print(f"Updated {key} with last_xmin = {new_xmin}")


# Example Test:
current_last_xmin = get_last_synced_xmin(table)
print(f"Fetched last_xmin: {current_last_xmin}")

No previous state found for 'customers'. Defaulting last_xmin to 0.
Fetched last_xmin: 0

#### Now create upload_static_tables() function with metadata and xmin checkup

In [38]:
def upload_static_tables_v2(tables_to_snapshot: list = None):

    if tables_to_snapshot is None:
        tables_to_snapshot = ["customers", "sellers", "products"]

    schema = "public"
    engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])
    bronze_bucket = CONFIG["storage"]["bronze_bucket"]

    with engine.connect() as conn:
        for table in tables_to_snapshot:
            print(f"\n--- [Snapshot] Checking table: {table} ---")

            # First of all check the xmin value for the table
            xmin_query = text(f"SELECT MAX(xmin::text::bigint) FROM {schema}.{table}")
            current_max_xmin = conn.execute(xmin_query).scalar()

            # Get the last saved xmin
            last_xmin_value = get_last_synced_xmin(table)

            # Check for the update in table by comparing the current xmin and last saved xmin
            if current_max_xmin is None or current_max_xmin <= last_xmin_value:
                print(f"No changes in '{table}'. Skipping snapshot.")
                continue

            print(f"Extracting '{table}' (xmin: {last_xmin_value} -> {current_max_xmin})...")

            # Extract data from the database as df using pd.read_sql()
            df = pd.read_sql(f"SELECT * FROM {schema}.{table}", conn)

            # Create an in-memory bytes buffer
            buffer = io.BytesIO()
            # Write the DataFrame to the buffer as a Parquet file
            df.to_parquet(buffer, engine="pyarrow", index=False)
            # Reset the buffer's cursor back to the beginning
            buffer.seek(0)

            # Generate Hive-partitioned S3 Key (File path)
            now = datetime.now()
            snapshot_date = now.strftime("%Y-%m-%d")
            snapshot_time = now.strftime("%H%M%S")  # e.g., 114220

            s3_key = f"postgres/snapshots/table_name={table}/snapshot_date={snapshot_date}/snapshot_{snapshot_time}.parquet"

            # Upload to MinIO
            print(f"Uploading {table} to bucket: {bronze_bucket}")
            print(f"Target Path: {s3_key}")

            s3.put_object(
                Bucket=bronze_bucket,
                Key=s3_key,
                Body=buffer.getvalue(),
            )

            # Finally update the xmin value to current xmin in s3 metadata
            update_synced_xmin(table, current_max_xmin)

            print(f"Uploaded to s3://{bronze_bucket}/{s3_key}")

In [39]:
upload_static_tables_v2()

--- [Snapshot] Checking table: customers ---
No previous state found for 'customers'. Defaulting last_xmin to 0.
Extracting 'customers' (xmin: 0 -> 753)...
Uploading customers to bucket: raw-bronze
Target Path: postgres/snapshots/table_name=customers/snapshot_date=2026-08-20/snapshot_074632.parquet
Updated metadata/table_name=customers/state.json with last_xmin = 753
Uploaded to s3://raw-bronze/postgres/snapshots/table_name=customers/snapshot_date=2026-08-20/snapshot_074632.parquet

--- [Snapshot] Checking table: sellers ---
No previous state found for 'sellers'. Defaulting last_xmin to 0.
Extracting 'sellers' (xmin: 0 -> 753)...
Uploading sellers to bucket: raw-bronze
Target Path: postgres/snapshots/table_name=sellers/snapshot_date=2026-08-20/snapshot_074633.parquet
Updated metadata/table_name=sellers/state.json with last_xmin = 753
Uploaded to s3://raw-bronze/postgres/snapshots/table_name=sellers/snapshot_date=2026-08-20/snapshot_074633.parquet

--- [Snapshot] Checking table: products ---
No previous state found for 'products'. Defaulting last_xmin to 0.
Extracting 'products' (xmin: 0 -> 753)...
Uploading products to bucket: raw-bronze
Target Path: postgres/snapshots/table_name=products/snapshot_date=2026-08-20/snapshot_074633.parquet
Updated metadata/table_name=products/state.json with last_xmin = 753
Uploaded to s3://raw-bronze/postgres/snapshots/table_name=products/snapshot_date=2026-08-20/snapshot_074633.parquet

In [40]:
# upload_static_tables_v2()
print(CONFIG.keys())
print(json.dumps(CONFIG, indent=2, default=str))

dict_keys(['simulation', 'database', 'pgadmin', 'api', 'storage'])
{
  "simulation": {
    "sim_speed": 3600,
    "preload_watermark": "2017-01-15 00:00:00",
    "data_dir": "./producer/data"
  },
  "database": {
    "oltp": {
      "host": "localhost",
      "port": "5432",
      "name": "oltp_db",
      "user": "your_user_name",
      "password": "your_postgres_password",
      "oltp_url": "postgresql+psycopg2://your_user_name:your_postgres_password@localhost:5432/oltp_db"
    },
    "analytics": {
      "host": "localhost",
      "port": "5433",
      "name": "analytics_db",
      "user": "your_user_name",
      "password": "your_postgres_password",
      "analytics_url": "postgresql+psycopg2://your_user_name:your_postgres_password@localhost:5433/analytics_db"
    }
  },
  "pgadmin": {
    "email": "",
    "password": ""
  },
  "api": {
    "fastapi_url": "http://localhost:8001"
  },
  "storage": {
    "minio_endpoint": "http://localhost:9090",
    "minio_root_user": "minio_admin",
    "minio_root_password": "minio_admin_password",
    "minio_access_key": "MEcSmh2fx24kgGFkVRiS",
    "minio_secret_key": "Js7AdcIz58nwTnfJtNchQQ6YljnhDxXxzqI3MhoR",
    "shared_bucket": "pay-review",
    "bronze_bucket": "raw-bronze"
  }
}

### Step 5: Extracting Dynamic Data with Incremental Watermarking

Unlike our static/master tables, `orders` and `order_items` are **high-velocity transactional tables**. New rows are appended continuously by the simulation, so pulling the *entire* table on every run would be wasteful, slow, and would eventually crash our pipeline as volume grows.

#### The Watermark Strategy

Instead of asking "give me everything," we ask the database: *"give me only what's new since the last time I checked."*

To do this, we track a **watermark** — the maximum value of a strictly increasing column (in our case, `order_purchase_timestamp` for `orders`) from the previous run. On each new run:

1. Read the last saved watermark from our metadata state file.
2. Query only rows where the timestamp column is **greater than** the watermark.
3. If new rows are returned, convert them to Parquet and upload to the `batches/` path.
4. Update the watermark to the new maximum timestamp seen in this batch.
5. If no new rows exist, skip the upload entirely — just like our `xmin` check for static tables.

#### Why Not `xmin` Here?

`xmin` works well for detecting *any* change (insert/update) in small reference tables. But for high-volume append-only transactional tables, a **business timestamp column** is more efficient and semantically meaningful — it lets us reason about "data since time X," which is exactly what incremental batch loading needs.

#### State Tracking for Watermarks

Just like our `xmin` state files, we'll persist the watermark in MinIO under the same `metadata/` prefix, keyed by table name:

$$\text{\texttt{s3://raw-bronze/metadata/table\_name=\{table\_name\}/watermark.json}}$$

```json
{
  "table": "orders",
  "last_watermark": "2026-08-04T11:42:20",
  "updated_at": "2026-08-04T12:00:00"
}
```

#### Incremental Extraction Path

Recall from our Extraction Strategy Matrix that incremental batches land in a distinct part of the Bronze layer, separate from snapshots:

*   *Incremental Path:* `postgres/batches/table_name=orders/batch_date=2026-08-04/batch_114220.parquet`

This separation keeps our lake organized: `snapshots/` always reflects "current state" tables, while `batches/` accumulates an append-only history of transactional events over time — useful for replaying or backfilling downstream Silver/Gold layers later.

#### Watermark Column Reference

| Table | Watermark Column | Type | Notes |
| :--- | :--- | :--- | :--- |
| `orders` | `order_purchase_timestamp` | `timestamp` | Monotonically increasing per new order |
| `order_items` | *(inherits from parent `order_id`)* | — | Typically joined/filtered via `orders` batch, or its own insertion timestamp if available |

> **Key Insight:** A good watermark column must be strictly increasing and never updated retroactively. If a column can be edited after insert (e.g., `order_status`), it's a poor watermark candidate — you'd risk missing rows that were quietly updated without bumping the timestamp.

#### Why `order_items` Needs a Join

`order_items` doesn't have its own timestamp column — it inherits timing from its parent `orders` row. So to filter `order_items` incrementally, we join back to `orders` and filter on `orders.order_purchase_timestamp`.

In [27]:
high_velocity_tables = ["orders", "order_item"]

schema = "public"
engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])

#### Reading and Writing the Watermark State

Just like our `xmin` state file for static tables, we'll persist the watermark in MinIO under `metadata/table_name={table}/watermark.json`. Let's test fetching and saving a watermark for the `orders` table before we wrap it into a function.

In [28]:
table = "orders"
state_key = f"metadata_test/table_name={table}/watermark.json"
bronze_bucket = CONFIG["storage"]["bronze_bucket"]

DEFAULT_WATERMARK = "1970-01-01 00:00:00"

try:
    response = s3.get_object(Bucket=bronze_bucket, Key=state_key)
    state_data = json.loads(response["Body"].read().decode("utf-8"))
    last_watermark = state_data.get("last_watermark", DEFAULT_WATERMARK)
    print(f"Found existing watermark: {last_watermark}")
except ClientError as e:
    if e.response["Error"]["Code"] == "NoSuchKey":
        last_watermark = DEFAULT_WATERMARK
        print(f"No previous watermark found. Defaulting to: {last_watermark}")
    else:
        raise e

Found existing watermark: 2016-08-01 00:00:00

In [29]:
test_watermark = "2016-08-01 00:00:00"

payload = json.dumps({
    "table": table,
    "last_watermark": test_watermark,
    "updated_at": datetime.now().isoformat(),
})

s3.put_object(
    Bucket=bronze_bucket,
    Key=state_key,
    Body=payload.encode("utf-8"),
    ContentType="application/json",
)

print(f"Saved watermark for '{table}': {test_watermark}")

Saved watermark for 'orders': 2016-08-01 00:00:00

#### Testing the Incremental Query

Now let's run the actual delta query against `orders` using the watermark we just fetched, to confirm we only get rows newer than it.

In [30]:
table = "orders"
last_watermark = "2018-08-01 00:00:00" 

query_orders = text("""
    SELECT *
    FROM public.orders
    WHERE order_purchase_timestamp > :watermark
    ORDER BY order_purchase_timestamp ASC
 """)
with engine.connect() as conn:
    df_orders_delta = pd.read_sql(sql = query_orders,con=conn, params={"watermark":last_watermark})

print(f"Rows fetched from orders: {len(df_orders_delta)}")
display(df_orders_delta.head())

Rows fetched from orders: 0

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [31]:
table = "order_items"
last_watermark = "2018-08-01 00:00:00"   

query_order_items = text("""
    SELECT public.order_items.*, o.order_purchase_timestamp
    FROM public.order_items
    JOIN public.orders o ON order_items.order_id = o.order_id
    WHERE o.order_purchase_timestamp > :watermark
    ORDER BY o.order_purchase_timestamp ASC
""")

with engine.connect() as conn:
    df_items_delta = pd.read_sql(query_order_items, conn, params={"watermark": last_watermark})

print(f"Rows fetched from order_items: {len(df_items_delta)}")
display(df_items_delta.head())

Rows fetched from order_items: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, order_purchase_timestamp]
Index: []

#### The Problem With Writing It This Way

Look closely at the two cells above. They're *almost* identical:

- Both fetch a watermark.
- Both build a `SELECT ... WHERE <ts_col> > :watermark` query.
- Both run it through `pd.read_sql`.

The only things that actually differ between `orders` and `order_items` are:
1. Which **column** we filter on (`order_purchase_timestamp` vs `o.order_purchase_timestamp`).
2. Whether a **JOIN** is needed at all (`orders` needs none, `order_items` needs one back to `orders`).

If we kept writing a brand-new, hardcoded `text(...)` block for every high-velocity table, our code would grow linearly with every new table we add — and any bug fix (say, a change to how we handle NULL timestamps) would need to be copy-pasted into every single query block.

**This is exactly the signal that we should extract the *varying parts* into data, and keep the *query shape* as one reusable piece of code.**

That's the motivation for representing each table as a small config:

```python
{
    "ts_col": "...",     # which column to filter/order on
    "join_sql": "..."    # empty string if no join is needed, otherwise the JOIN clause
}
```

Now instead of two separate query blocks, we get **one query template** that's parameterized by table:

In [32]:
high_velocity_tables = {
    "orders": {
        "ts_col": "order_purchase_timestamp",
        "join_sql": ""
    },
    "order_items": {
        "ts_col": "o.order_purchase_timestamp",
        "join_sql": "JOIN public.orders o ON order_items.order_id = o.order_id"
    }
}

schema = "public"

for table, config in high_velocity_tables.items():
    ts_col = config["ts_col"]
    join_sql = config["join_sql"]

    query = text(f"""
        SELECT {schema}.{table}.*, {ts_col} as tracking_ts
        FROM {schema}.{table}
        {join_sql}
        WHERE {ts_col} > :watermark
        ORDER BY {ts_col} ASC
    """)

    with engine.connect() as conn:
        df_delta = pd.read_sql(query, conn, params={"watermark": "2018-01-01 00:00:00"})

    display(df_delta.head(5))
    print(f"[{table}] Rows fetched: {len(df_delta)}")

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, tracking_ts]
Index: []

[orders] Rows fetched: 0

Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value, tracking_ts]
Index: []

[order_items] Rows fetched: 0

Notice we now have **one query template and one loop**, instead of one hardcoded block per table. Adding a third high-velocity table later just means adding one new dictionary entry — no new SQL block, no copy-pasting.

#### Deriving the New Watermark

Once we have the delta rows, the new watermark is simply the **maximum** value of `order_purchase_timestamp` in the batch we just pulled. We then drop that helper column before writing to Parquet, since it isn't part of the original table schema.

In [33]:
if not df_orders_delta.empty:
    max_new_watermark = df_orders_delta["order_purchase_timestamp"].max()
    df_orders_delta = df_orders_delta.drop(columns=["order_purchase_timestamp"])
    print(f"New watermark would be: {max_new_watermark}")
else:
    print("No new rows — watermark stays unchanged.")

No new rows — watermark stays unchanged.

#### Now Let's Formalize This Into Reusable Functions

We'll split the logic into three pieces, mirroring the pattern we used for `xmin`:

1. `get_last_watermark(table)` — reads the saved watermark from MinIO.
2. `update_watermark(table, max_timestamp)` — writes the new watermark back to MinIO.
3. `upload_incremental_tables(high_velocity_tables, schema)` — loops through the tables, checks the watermark, extracts only new rows, and uploads them as Parquet.

Fill in the blanks below using the raw code we just tested above.

In [51]:
bronze_bucket = CONFIG["storage"]["bronze_bucket"]
engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])

In [49]:
import json
from datetime import datetime, timezone
from botocore.exceptions import ClientError

DEFAULT_WATERMARK = "1970-01-01 00:00:00"


def get_last_watermark(table_name):
    """Fetch stored timestamp watermark from S3 state file."""
    key = f"metadata_test/table_name={table_name}/watermark.json"
    try:
        response = s3.get_object(Bucket=CONFIG["storage"]["bronze_bucket"], Key=key)
        state_data = json.loads(response["Body"].read().decode("utf-8"))
        return state_data.get("last_watermark", DEFAULT_WATERMARK)
    except ClientError as e:
        if e.response["Error"]["Code"] == "NoSuchKey":
            print(f"No previous watermark found for '{table_name}'. Defaulting to epoch.")
            return DEFAULT_WATERMARK
        raise e


def update_watermark(table_name, max_timestamp):
    """Save the latest timestamp watermark to S3 state file."""
    key = f"metadata_test/table_name={table_name}/watermark.json"
    payload = json.dumps({
        "table_name": table_name,
        "last_watermark": str(max_timestamp),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    })

    s3.put_object(
        Bucket=CONFIG["storage"]["bronze_bucket"],
        Key=key,
        Body=payload,
        ContentType="application/json",
    )
    print(f"Updated {key} with last_watermark = {max_timestamp}")

In [53]:
update_watermark(table_name= "customers", max_timestamp="2024-01-01 00:00:00")

Updated metadata_test/table_name=customers/watermark.json with last_watermark = 2024-01-01 00:00:00

In [54]:
get_last_watermark(table_name="test_table")

No previous watermark found for 'test_table'. Defaulting to epoch.

'1970-01-01 00:00:00'

In [65]:
import io
import json
from datetime import datetime, timezone
import pandas as pd
from sqlalchemy import create_engine, text

def upload_incremental_tables(high_velocity_tables: dict = None, schema: str = None):
    """
    Extracts incremental delta records from high-velocity tables using timestamp
    watermarks, uploading only new rows to MinIO as Parquet.
    """
    if high_velocity_tables is None:
        high_velocity_tables = {
            "orders": {
                "ts_col": "order_purchase_timestamp",
                "join": None,
            },
            "order_items": {
                "ts_col": "o.order_purchase_timestamp",
                "join": "JOIN orders o ON order_items.order_id = o.order_id",
            },
        }

    schema = schema or "public"
    engine = create_engine(CONFIG["database"]["oltp"]["oltp_url"])
    bronze_bucket = CONFIG["storage"]["bronze_bucket"]

    with engine.connect() as conn:
        for table, config in high_velocity_tables.items():
            ts_col = config['ts_col']
            join_sql = config.get("join") or ""

            print(f"\n--- [Incremental] Processing Table: {table} ---")

            # Fetch the last saved watermark
            last_watermark = get_last_watermark(table)

            # Build and run the delta query
            query = text(f"""
                SELECT {schema}.{table}.*, {ts_col} AS tracking_ts
                FROM {schema}.{table}
                {join_sql}
                WHERE {ts_col} > :watermark
                ORDER BY {ts_col} ASC
            """)

            # Read the table from database
            df = pd.read_sql(query, conn, params={"watermark": last_watermark})

            if df.empty:
                print(f"No new rows found in '{table}'. Skipping batch.")
                continue

            # Derive new watermark and drop the helper column
            max_new_watermark = df["tracking_ts"].max()
            df = df.drop(columns=["tracking_ts"])

            print(f"Extracted {len(df)} new records (New Max Watermark: {max_new_watermark})")

            # Convert to Parquet in-memory
            buffer = io.BytesIO()
            df.to_parquet(buffer, index=False, engine="pyarrow")
            buffer.seek(0)

            # Build Hive-partitioned S3 key
            now = datetime.now()
            s3_key = (
                f"postgres/batches/table_name={table}/"
                f"batch_date={now.strftime('%Y-%m-%d')}/batch_{now.strftime('%H%M%S')}.parquet"
            )

            # Upload to MinIO
            print(f"Uploading {table} to bucket: {bronze_bucket}")
            print(f"Target Path: {s3_key}")
            s3.put_object(
                Bucket=bronze_bucket,
                Key=s3_key,
                Body=buffer.getvalue(),
            )

            # Update the watermark state
            update_watermark(table_name=table, max_timestamp=max_new_watermark)

            print(f"✅ Batch uploaded to s3://{bronze_bucket}/{s3_key}")

In [78]:
upload_incremental_tables()

--- [Incremental] Processing Table: orders ---
Extracted 126 new records (New Max Watermark: 2017-03-08 09:10:55)
Uploading orders to bucket: raw-bronze
Target Path: postgres/batches/table_name=orders/batch_date=2026-08-20/batch_090202.parquet
Updated metadata_test/table_name=orders/watermark.json with last_watermark = 2017-03-08 09:10:55
✅ Batch uploaded to s3://raw-bronze/postgres/batches/table_name=orders/batch_date=2026-08-20/batch_090202.parquet

--- [Incremental] Processing Table: order_items ---
Extracted 143 new records (New Max Watermark: 2017-03-08 09:10:55)
Uploading order_items to bucket: raw-bronze
Target Path: postgres/batches/table_name=order_items/batch_date=2026-08-20/batch_090202.parquet
Updated metadata_test/table_name=order_items/watermark.json with last_watermark = 2017-03-08 09:10:55
✅ Batch uploaded to s3://raw-bronze/postgres/batches/table_name=order_items/batch_date=2026-08-20/batch_090202.parquet

### Step 6: Formalizing Everything into `postgres_extractor.py`

So far we've built and tested our extraction logic directly inside the notebook — first exploring raw queries, then wrapping them into standalone functions (`upload_static_tables_v2`, `upload_incremental_tables`). That's great for learning and experimentation, but a production pipeline shouldn't live inside a notebook.

It's time to move this logic into a proper Python module: **`extractor/postgres_extractor.py`**.

#### Why Classes Now?

Notice that both our snapshot logic (`xmin`-based) and our incremental logic (watermark-based) share the same overall shape:

1. Connect to Postgres.
2. Loop over a set of tables.
3. Check some form of "state" (either `xmin` or a `watermark`) to decide if extraction is needed.
4. If needed, extract → convert to Parquet → upload to MinIO.
5. Update the state file in MinIO.

Wrapping each strategy in its own class lets us:
- Keep **state-reading and state-writing** as small private helper methods (`_get_last_synced_xmin`, `_update_watermark`, etc.), instead of scattering `s3.get_object`/`s3.put_object` calls everywhere.
- Reuse the shared MinIO connection and bucket-checking logic from `BaseExtractor` (the same class you already implemented in Step 1), instead of duplicating it in every extractor.
- Give each extractor a single, predictable entry point: `.run()`.

#### What You'll Build

Two classes, both inheriting from `BaseExtractor`:

| Class | Strategy | Tables | State File |
| :--- | :--- | :--- | :--- |
| `PostgresSnapshotExtractor` | `xmin`-based change detection | `customers`, `products`, `sellers` | `metadata/table_name={table}/state.json` |
| `PostgresIncrementalExtractor` | Timestamp watermarking | `orders`, `order_items` | `metadata/table_name={table}/watermark.json` |

Use the logic we already tested cell-by-cell in this notebook — you're not writing anything new, just organizing and porting what already works.

### Before We Move Into `.py` Files: A Note on Logging

Up to this point, every cell in this notebook has used `print()` to show status — and that's fine, because a notebook is an interactive exploration space. You're watching the output as you go, cell by cell, so `print()` is simple and immediate.

**From here on, as we move this logic into reusable modules (`postgres_extractor.py`, `api_extractor.py`), we're going to switch to Python's `logging` module instead of `print()`.**

Why the switch?

Once this code becomes a `.py` file meant to run unattended — inside a Docker container, an Prefect task, a scheduled cron job — nobody is watching the terminal live the way you're watching this notebook. `print()` output has no severity level, no timestamp, and can't easily be redirected, filtered, or routed anywhere useful. `logging` solves all of this:

- **Severity levels** (`INFO`, `WARNING`, `ERROR`) let you filter noise from real problems.
- **Timestamps** tell you exactly *when* something happened, which matters when debugging a pipeline that ran overnight.
- **The module name** in every log line tells you exactly *where* a message came from.
- **Flexible output** — logs can go to a file, stdout, or a remote log aggregator (CloudWatch, Datadog, etc.) without touching your actual pipeline code.

**Rule of thumb going forward in this course:** `print()` for throwaway exploration in a notebook cell, `logger` for anything that lives in a class or script meant to run in production.

With that in mind, let's build `postgres_extractor.py` — this time with proper `logger.info(...)` / `logger.warning(...)` / `logger.error(...)` calls instead of `print()`.